-- MySQL Script generated by MySQL Workbench
-- Fri Oct 26 08:06:14 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdcolchoneria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdcolchoneria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdcolchoneria` DEFAULT CHARACTER SET latin1 ;
USE `bdcolchoneria` ;

-- -----------------------------------------------------
-- Table `bdcolchoneria`.`tbl_modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcolchoneria`.`tbl_modulo` (
  `PK_Modulo_codigo` INT(11) NOT NULL,
  `modulo_nombre` VARCHAR(45) NULL DEFAULT NULL,
  `modulo_estado` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Modulo_codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bdcolchoneria`.`tbl_aplicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcolchoneria`.`tbl_aplicacion` (
  `PK_Api_codigo` INT(11) NOT NULL,
  `api_descripcion` VARCHAR(45) NOT NULL,
  `FK_Codigo_modulo` INT(11) NOT NULL,
  `api_estado` INT(11) NOT NULL,
  PRIMARY KEY (`PK_Api_codigo`),
  INDEX `aplicacion_modulo_modulo_codigo_fk` (`FK_Codigo_modulo` ASC),
  CONSTRAINT `aplicacion_modulo_modulo_codigo_fk`
    FOREIGN KEY (`FK_Codigo_modulo`)
    REFERENCES `bdcolchoneria`.`tbl_modulo` (`PK_Modulo_codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bdcolchoneria`.`tbl_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcolchoneria`.`tbl_usuario` (
  `PK_Usu_Codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `usu_nickname` VARCHAR(45) NULL DEFAULT NULL,
  `usu_password` VARCHAR(45) NULL DEFAULT NULL,
  `usu_estado` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Usu_Codigo`),
  UNIQUE INDEX `usuario_usu_nickname_uindex` (`usu_nickname` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bdcolchoneria`.`tbl_bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcolchoneria`.`tbl_bitacora` (
  `PK_Bitacora_Correlativo` INT(11) NOT NULL AUTO_INCREMENT,
  `FK_Usuario_Codigo` INT(11) NOT NULL,
  `Nombre_Usu_Bit` VARCHAR(45) NULL,
  `host` VARCHAR(35) NULL DEFAULT NULL,
  `num_aplicacion` INT(11) NOT NULL,
  `accion` VARCHAR(35) NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Bitacora_Correlativo`),
  INDEX `bitacora_usuario_usuario_codigo_fk` (`FK_Usuario_Codigo` ASC),
  CONSTRAINT `bitacora_usuario_usuario_codigo_fk`
    FOREIGN KEY (`FK_Usuario_Codigo`)
    REFERENCES `bdcolchoneria`.`tbl_usuario` (`PK_Usu_Codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bdcolchoneria`.`tbl_doc_asociado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcolchoneria`.`tbl_doc_asociado` (
  `PK_Id_Documento` INT(11) NOT NULL,
  `Nombre_doc` VARCHAR(45) NULL DEFAULT NULL,
  `Ruta` VARCHAR(45) NULL DEFAULT NULL,
  `FK_Api_codigo` INT(11) NOT NULL,
  `doc_estado` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Id_Documento`, `FK_Api_codigo`),
  UNIQUE INDEX `id_documento` (`PK_Id_Documento` ASC),
  INDEX `fk_Doc_asociado_aplicacion1_idx` (`FK_Api_codigo` ASC),
  CONSTRAINT `fk_Doc_asociado_aplicacion1`
    FOREIGN KEY (`FK_Api_codigo`)
    REFERENCES `bdcolchoneria`.`tbl_aplicacion` (`PK_Api_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bdcolchoneria`.`tbl_perfil_encabezado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcolchoneria`.`tbl_perfil_encabezado` (
  `PK_perf_cod_encabezado` INT(11) NOT NULL,
  `perf_nombre` VARCHAR(45) NULL DEFAULT NULL,
  `perf_estado` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_perf_cod_encabezado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bdcolchoneria`.`tbl_perfil_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcolchoneria`.`tbl_perfil_detalle` (
  `PK_correlativo` INT(11) NOT NULL AUTO_INCREMENT,
  `FK_perf_cod_encabezado` INT(11) NOT NULL,
  `FK_Api_codigo` INT(11) NOT NULL,
  `ingresar` INT(1) NOT NULL,
  `editar` INT(1) NOT NULL,
  `guardar` INT(1) NOT NULL,
  `borrar` INT(1) NOT NULL,
  `consultar` INT(1) NOT NULL,
  PRIMARY KEY (`PK_correlativo`),
  INDEX `perfil_detalle_perfil_encabezado_perf_cod_encabezado_fk` (`FK_perf_cod_encabezado` ASC),
  INDEX `perfil_detalle_aplicacion_api_codigo_fk` (`FK_Api_codigo` ASC),
  CONSTRAINT `perfil_detalle_aplicacion_api_codigo_fk`
    FOREIGN KEY (`FK_Api_codigo`)
    REFERENCES `bdcolchoneria`.`tbl_aplicacion` (`PK_Api_codigo`),
  CONSTRAINT `perfil_detalle_perfil_encabezado_perf_cod_encabezado_fk`
    FOREIGN KEY (`FK_perf_cod_encabezado`)
    REFERENCES `bdcolchoneria`.`tbl_perfil_encabezado` (`PK_perf_cod_encabezado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bdcolchoneria`.`tbl_relacion_usuario_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcolchoneria`.`tbl_relacion_usuario_perfil` (
  `FK_Usu_Codigo` INT(11) NULL DEFAULT NULL,
  `FK_perf_codigo` INT(11) NULL DEFAULT NULL,
  INDEX `relacion_usuario_perfil_usuario_usu_codigo_fk` (`FK_Usu_Codigo` ASC),
  INDEX `relacion_usuario_perfil_perfil_encabezado_perf_cod_encabezado_fk` (`FK_perf_codigo` ASC),
  CONSTRAINT `relacion_usuario_perfil_perfil_encabezado_perf_cod_encabezado_fk`
    FOREIGN KEY (`FK_perf_codigo`)
    REFERENCES `bdcolchoneria`.`tbl_perfil_encabezado` (`PK_perf_cod_encabezado`),
  CONSTRAINT `relacion_usuario_perfil_usuario_usu_codigo_fk`
    FOREIGN KEY (`FK_Usu_Codigo`)
    REFERENCES `bdcolchoneria`.`tbl_usuario` (`PK_Usu_Codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
